### ISSUE TITLE
как инжектать

### ISSUE THREAD

**Issue by discographi** [cafeed28/BoolkaSDK#2]
я позер

**Comment by cafeed28** [comment]
на ведре или на пк?

**Comment by discographi** [comment]
> на ведре или на пк?

и там и там

**Comment by cafeed28** [comment]
на ведре описано в ридми, на пк любой лодер, я потом напишу свой

**Comment by discographi** [comment]
пидор блять иссуе не закрывай

**Comment by cafeed28** [comment]
нахуя она

**Comment by discographi** [comment]
вышел лоадер, теперь как инжектить

**Comment by cafeed28** [comment]
лодером🤌
